### ISSUE TITLE
Are you still maintaining this?

### ISSUE THREAD

**Issue by galatzan** [ErikEvenson/googleads-node-lib#5]
Hey Erik,

First of all, congrats on the good work! I wanted to check if you continue to maintain this project? If not, do you know of any other good ones?

Thanks!

**Comment by ErikEvenson** [comment]
@galatzan I don't do much work with the Google Ads API anymore, so my work on this is really hit and miss these days.  I hope you can get some value out of it being here there as a fork or for ideas going forward.
